replicaCount: 2

image:
  name: house-innovations-housnav-web
  repository: ""
  tag: ""
  pullPolicy: Always

imagePullSecrets:
  - name: ""

service:
  type: ClusterIP
  port: 80
  targetPort: 3000

livenessProbe:
  initialDelaySeconds: 30
  periodSeconds: 10

readinessProbe:
  initialDelaySeconds: 30
  periodSeconds: 10

networkPolicy:
  enabled: true

resources:
  requests:
    memory: "50Mi"
    cpu: "25m"
  limits:
    memory: "100Mi"
    cpu: "50m"
