replicaCount: 2

livenessProbe:
  initialDelaySeconds: 30
  periodSeconds: 10

readinessProbe:
  initialDelaySeconds: 30
  periodSeconds: 10

resources:
  requests:
    memory: "100Mi"
    cpu: "100m"
  limits:
    memory: "200Mi"
    cpu: "300m"

vault:
  secretPath: d6af69-nonprod/housnav-secret-dev
  authPath: auth/k8s-silver
  namespace: platform-services
  role: d6af69-nonprod
  serviceAccountName: d6af69-vault

route:
  hostName: dev.buildcodenavigator.gov.bc.ca

hpa:
  enabled: true
  minReplicas: 2
  maxReplicas: 5
  targetCPUUtilizationPercentage: 80
  targetMemoryUtilizationPercentage: 80