replicaCount: 1

image:
  name: house-innovations-housnav-web
  repository: ${ARTIFACTORY_REPOSITORY}
  tag: "fa62c85"
  pullPolicy: IfNotPresent

imagePullSecrets:
  - name: ${IMAGE_PULL_SECRET_NAME}

service:
  type: ClusterIP
  port: 8081
  targetPort: 3000

livenessProbe:
  initialDelaySeconds: 30
  periodSeconds: 10

readinessProbe:
  initialDelaySeconds: 30
  periodSeconds: 10

resources: {}

# nodeSelector: {}

# tolerations: []

# affinity: {}
