replicaCount: 2

livenessProbe:
  initialDelaySeconds: 30
  periodSeconds: 10

readinessProbe:
  initialDelaySeconds: 30
  periodSeconds: 10

resources:
  requests:
    memory: "50Mi"
    cpu: "25m"
  limits:
    memory: "100Mi"
    cpu: "50m"

vault:
  secretPath: d6af69-nonprod/housnav-secret-uat
  authPath: auth/k8s-silver
  namespace: platform-services
  role: d6af69-nonprod
  serviceAccountName: d6af69-vault

route:
  hostName: test.buildcodenavigator.gov.bc.ca