apiVersion: v1
kind: Service
metadata:
  name: house-innovations-housnav-web-service
spec:
  selector:
    app: house-innovations-housnav-web
  ports:
    - protocol: TCP
      port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetPort }}
