{{- if .Values.vpa.enabled }}
apiVersion: autoscaling.k8s.io/v1
kind: VerticalPodAutoscaler
metadata:
  name: house-innovations-housnav-web-vpa
spec:
  targetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: house-innovations-housnav-web-deployment
  updatePolicy:
    updateMode: "{{ .Values.vpa.mode }}"
  resourcePolicy:
    containerPolicies:
      - containerName: {{ .Chart.Name }}
        minAllowed:
          cpu: {{ .Values.vpa.minAllowed.cpu }}
          memory: {{ .Values.vpa.minAllowed.memory }}
        maxAllowed:
          cpu: {{ .Values.vpa.maxAllowed.cpu }}
          memory: {{ .Values.vpa.maxAllowed.memory }}
{{- end }}
