name: Build-and-Test

on:
  pull_request:
    branches:
      - main
  workflow_dispatch:
    inputs:
      pr-number:
        description: "PR Number"
        required: true

jobs:
  run-unit-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "18.x"

      - name: Install Dependencies
        run: npm ci

      - name: Run Unit Tests
        run: npm run test

  build:
    needs: run-unit-tests
    runs-on: ubuntu-latest
    environment: dev
    outputs:
      pr-number-output: ${{ steps.set-output.outputs.pr-number }}
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v2

      ### Not recommended to use the PR number Docker tag in production.
      ### Use only for dev and UAT
      - name: Set PR Number
        id: set-pr-number
        run: |
          if [ -z "${{ github.event.inputs.pr-number }}" ]; then
            if [ -z "${{ github.event.number }}" ]; then
              echo "PR number is empty. Failing workflow."
              exit 1
            else
              echo "pr-number=${{ github.event.number }}" >> $GITHUB_OUTPUT
            fi
          else
            echo "pr-number=${{ github.event.inputs.pr-number }}" >> $GITHUB_OUTPUT
          fi

      - name: Build Docker Image
        run: docker build -t ${{ vars.ARTIFACTORY_URL }}/${{ secrets.ARTIFACTORY_REPOSITORY_NAME }}/house-innovations-housnav-web:${{ steps.set-pr-number.outputs.pr-number }} -f apps/web/Dockerfile . --no-cache

      - name: Run Docker Container
        run: docker run -d -p 3000:3000 --name housnav ${{ vars.ARTIFACTORY_URL }}/${{ secrets.ARTIFACTORY_REPOSITORY_NAME }}/house-innovations-housnav-web:${{ steps.set-pr-number.outputs.pr-number }}

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "18.x"

      - name: Install Dependencies
        run: npm ci

      - name: Run Cypress End-to-End Tests
        run: npm run e2e:chrome
        working-directory: ./apps/web

      - name: Upload Cypress Screenshots on Failure
        uses: actions/upload-artifact@v4
        if: failure()
        with:
          name: cypress-snapshots
          path: apps/web/cypress/screenshots

      - name: Stop Docker Container
        run: docker stop housnav

      - name: Run Trivy Vulnerability Scan
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: ${{ vars.ARTIFACTORY_URL }}/${{ secrets.ARTIFACTORY_REPOSITORY_NAME }}/house-innovations-housnav-web:${{ steps.set-pr-number.outputs.pr-number }}
          format: table
          exit-code: '0'
          ignore-unfixed: true
          vuln-type: os,library
          severity: "CRITICAL,HIGH"

      - name: Login to Artifactory
        uses: docker/login-action@v3
        with:
          registry: ${{ vars.ARTIFACTORY_URL }}
          username: ${{ secrets.ARTIFACTORY_SERVICEACCOUNT_USERNAME }}
          password: ${{ secrets.ARTIFACTORY_SERVICEACCOUNT_PASSWORD }}

      - name: Push Docker Image to Artifactory
        run: docker push ${{ vars.ARTIFACTORY_URL }}/${{ secrets.ARTIFACTORY_REPOSITORY_NAME }}/house-innovations-housnav-web:${{ steps.set-pr-number.outputs.pr-number }}

