name: Build-and-Test

on:
  pull_request:
    branches:
      - main
    paths-ignore:
      - '.github/**'
  workflow_dispatch: # This allows you to manually trigger the workflow

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: use node.js
        uses: actions/setup-node@v3
        with:
          node-version: "18.x"
      - run: npm ci
      - run: npm run test

  build:
    needs: test
    runs-on: ubuntu-latest
    environment: dev
    outputs:
      short-commit-hash: ${{ steps.extract-commit-hash.outputs.short-git-sha }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Extract Git commit hash
        id: extract-commit-hash
        run: echo "short-git-sha=$(git rev-parse --short HEAD)" >> $GITHUB_OUTPUT
      - name: Build Docker image
        run: docker build -t ${{ secrets.ARTIFACTORY_URL }}/${{ secrets.ARTIFACTORY_REPOSITORY_NAME }}/house-innovations-housnav-web:${{ steps.extract-commit-hash.outputs.short-git-sha }} -f apps/web/Dockerfile . --no-cache
      - name: Login to Artifactory image registry with Docker
        uses: docker/login-action@v3
        with:
          registry: ${{ secrets.ARTIFACTORY_URL }}
          username: ${{ secrets.ARTIFACTORY_SERVICEACCOUNT_USERNAME }}
          password: ${{ secrets.ARTIFACTORY_SERVICEACCOUNT_PASSWORD }}
      - name: Push Docker image to Artifactory
        run: docker push ${{ secrets.ARTIFACTORY_URL }}/${{ secrets.ARTIFACTORY_REPOSITORY_NAME }}/house-innovations-housnav-web:${{ steps.extract-commit-hash.outputs.short-git-sha }}
      - name: Write Git commit hash to file
        run: echo "${{ steps.extract-commit-hash.outputs.short-git-sha }}" > "outputs.txt"
      - name: Upload outputs to Artifactory
        run: |
          curl -v -X PUT \
            --user ${{ secrets.ARTIFACTORY_SERVICEACCOUNT_USERNAME }}:${{ secrets.ARTIFACTORY_SERVICEACCOUNT_PASSWORD }} \
            --upload-file ./outputs.txt \
            https://${{ secrets.ARTIFACTORY_URL }}/artifactory/${{ secrets.ARTIFACTORY_REPOSITORY_NAME }}/outputs.txt

  cypress-run:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - run: npm ci
      - run: npm run dev &
      - run: npm run e2e
