name: Build-and-Test

on:
  pull_request:
    branches:
      - main
    paths-ignore:
      - '.github/**'
  workflow_dispatch:
    inputs:
      pr-number:
        description: 'PR Number'
        required: true

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: use node.js
        uses: actions/setup-node@v3
        with:
          node-version: "18.x"
      - run: npm ci
      - run: npm run test

  build:
    needs: test
    runs-on: ubuntu-latest
    environment: dev
    outputs:
      pr-number-output: ${{ steps.set-output.outputs.pr-number }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Set PR number
        id: set-pr-number
        run: |
          if [ -z "${{ github.event.inputs.pr-number }}" ]; then
            if [ -z "${{ github.event.number }}" ]; then
              echo "PR number is empty. Failing workflow."
              exit 1
            else
              echo "pr-number=${{ github.event.number }}" >> $GITHUB_OUTPUT
            fi
          else
            echo "pr-number=${{ github.event.inputs.pr-number }}" >> $GITHUB_OUTPUT
          fi
  
      - name: Build Docker image
        run: docker build -t ${{ vars.ARTIFACTORY_URL }}/${{ secrets.ARTIFACTORY_REPOSITORY_NAME }}/house-innovations-housnav-web:${{ steps.set-pr-number.outputs.pr-number }} -f apps/web/Dockerfile . --no-cache

      - name: Login to Artifactory image registry with Docker
        uses: docker/login-action@v3
        with:
          registry: ${{ vars.ARTIFACTORY_URL }}
          username: ${{ secrets.ARTIFACTORY_SERVICEACCOUNT_USERNAME }}
          password: ${{ secrets.ARTIFACTORY_SERVICEACCOUNT_PASSWORD }}

      - name: Push Docker image to Artifactory
        run: docker push ${{ vars.ARTIFACTORY_URL }}/${{ secrets.ARTIFACTORY_REPOSITORY_NAME }}/house-innovations-housnav-web:${{ steps.set-pr-number.outputs.pr-number }}

  cypress-run:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - run: npm ci
      - run: npm run dev &
      - run: npm run e2e
