name: Push Docker Image

on:
  workflow_run:
    workflows: ["Build and Tag Docker Image"]
    types:
      - completed
  workflow_dispatch: # Manual trigger
    inputs:
      trigger-push:
        description: 'Trigger the push'
        required: true
        default: 'true'

jobs:
  push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Verify Docker Image
        run: echo ${{ github.event.workflow_run.jobs.build.outputs.image_tag }}

#      - name: Log in to OpenShift
#        uses: docker/login-action@v1
#        with:
#          username: ${{ secrets.DOCKER_USERNAME }}
#          password: ${{ secrets.DOCKER_PASSWORD }}

#      - name: Push Docker Image
#        run: docker push ${{ needs.build.outputs.image_tag }}
