name: Build and Test

on:
  pull_request:
    branches:
      - main
  workflow_dispatch: # This allows you to manually trigger the workflow

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: use node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18.x'
      - run: npm ci
      - run: npm run test

  build:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Extract Git commit hash
        id: vars
        run: echo "GIT_SHA=$(git rev-parse --short HEAD)" >> $GITHUB_ENV
      - name: Build Docker image with commit hash for testing
        run: docker build -t house-innovations-housnav-web:${{ env.GIT_SHA }}-test -f apps/web/Dockerfile . --no-cache

  cypress-run:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - run: npm ci
      - run: npm run dev &
      - run: npm run e2e
